### ISSUE TITLE
kliknięcie w "Oznacz wszystko jako" nie oznacza wszystkich

### ISSUE THREAD

**Issue by jawnosc2016** [szkolny-eu/szkolny-android#104]
kliknięcie w "Oznacz wszystko jako" nie oznacza wszystkich bo jak to kliknąłem to dalej mam (3) na czerownym polu nad "Wiadomości"

**Comment by kuba2k2** [comment]
Wiadomości nie mogą oznaczać się jako przeczytane automatycznie. Wiadomość wymaga otwarcia oraz przeczytania, jest to celowe zachowanie.

**Comment by kuba2k2** [comment]
Bo "oznacz trochę jako" brzmi głupio i jest nielogiczne. A wypisywanie "oznacz oceny, wydarzenia, zadania, obecność, zachowanie i plan lekcji jako" chyba nie wymaga komentarza.
