### ISSUE TITLE
Add to f-droid

### ISSUE THREAD

**Issue by schrodinger44** [szkolny-eu/szkolny-android#119]
Since the app is banned from google play store (with librus), it would be nice to have an alternative option of keeping it updated, without checking relases. 

Here is a guide how to add: https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#adding-a-new-app

**Comment by Antoni-Czaplicki** [comment]
In fact, you can get updates directly from the app.

**Comment by schrodinger44** [comment]
will the app download apk from github release and prepare it for installation by user? even if that's true, in my opinion it is worth considering to add szkolny to f-droid catalogue, since it helps promoting free and open source software, and app like wulkanowy is already there.

**Comment by Antoni-Czaplicki** [comment]
yeah, but nobody wants to do that, if that's so important for you, do it yourself

**Comment by kuba2k2** [comment]
The app is not banned from Google Play store. It is updated there, whenever a new version is released. The app also contains a built-in updater, which notifies about new releases and allows to download and install them.

**Comment by kuba2k2** [comment]
Besides, F-droid requires a fully open source compilation environment, which is not really an option in this app, as it uses secret API keys which are not published in the source code repository, and are added dynamically by GitHub Actions during the automated release process.

**Comment by schrodinger44** [comment]
so even trying to remove or replace proprietary blobs won't be sufficient? bummer. i'm afraid i cannot replace keys or make user inputable?

**Comment by kuba2k2** [comment]
You cannot have "user inputable" keys, which are not even published in the repo. They just are private - it is the slightest possible security measure to protect the app's own server API from incorrect usage. The "source" code of the "proprietary blob" is actually present in the repo - still, it's missing some keys required for the API to work properly. These keys are added at compile time. Take a look at the GitHub Actions workflows and helper scripts for some details.

**Comment by schrodinger44** [comment]
my apologies, i have understood it as there are keys for all systems (librus, uonet, mobi) whereas proprietary blobs were meant to be google's crashlytics and play services. since there is no solution for this, i think the issue should be closed by now.
