### ISSUE TITLE
Error code: 147 (LibrusApiTeacherFreeDayTypes)

### ISSUE THREAD

**Issue by depablo** [szkolny-eu/szkolny-android#121]
Hi,

I am new user of this application (and it is great). I downloaded Edziennik_4.11_official.apk from official page. So I don't know if this is new issue or not.

Each time the data are synchronized this type of error appears:
Error code: 147 (LibrusApiTeacherFreeDayTypes)

I reported it with a report button, but there was no confirmation of sending so I am just writing this issue (just in case).

Thanks,
Paweł

**Comment by kuba2k2** [comment]
This most likely indicates a change in the e-register API. Since Librus is not officially maintained, you can ask the community to try to fix this issue. Or, you can create a fork and modify the application to suit your needs.

**Comment by kuba2k2** [comment]
Also, if you build something you think may be of use by the others, feel free to submit a PR to this repo.
