### ISSUE TITLE
Librus disabled notice on the GitHub version.

### ISSUE THREAD

**Issue by TheChilliPL** [szkolny-eu/szkolny-android#127]
I keep getting the notice saying that Librus is getting disabled on the GitHub version of the app. It just randomly stops working and I have to reinstall the app to make it update again.

In the app version info screen, it says distribution: Google Play, which is incorrect.

**Comment by TheChilliPL** [comment]
Seems like right after reinstalling manually it says distribution: APK correctly, so it must be getting replaced with the Google Play version for some reason

**Comment by kuba2k2** [comment]
There is no known to me solution for Google Play auto-updating apps, other than disabling auto-update on the app page, uninstalling the app completely in Google Play and then installing it again from APK. This should cause the app to "unlink" from the store, and still it's not confirmed to always work.
