### ISSUE TITLE
Material You/Material 3

### ISSUE THREAD

**Issue by MaximilianGaedig** [szkolny-eu/szkolny-android#131]
Fajnie by bylo jak by byl theme Material 3 z kolorami Material You albo chociaz theme uzywajace kolory Material You

**Comment by kuba2k2** [comment]
Jest to prawda

**Comment by MaximilianGaedig** [comment]
Wiem ze pewnie to sie nie stanie ale moze ktos bedzie sie nudzil :)

**Comment by kuba2k2** [comment]
#146
