### ISSUE TITLE
Nie działający moduł wiadomości (VULCAN)

### ISSUE THREAD

**Issue by PiotrLobo6780** [szkolny-eu/szkolny-android#132]
Po aktualizacji modułu wiadomości przez VULCANa nie widać wiadomości w aplikacji, jednak widnieją one na stronie internetowej dziennika (reinstalacja nie pomogła).

**Comment by kuba2k2** [comment]
Od września tego roku, Vulcan wprowadził duże zmiany w API, przez które dotychczasowa obsługa wiadomości w Szkolny.eu jest niekompatybilna.
