### ISSUE TITLE
[Vulcan] Po aktualizacji dziennik nie synchronizuje się

### ISSUE THREAD

**Issue by tadekdudek** [szkolny-eu/szkolny-android#135]
Za każdym razem przy próbie zsynchronizowania czegokolwiek pojawia się komunikat o błędzie:

"Błąd serwera: nieprawidłowe zapytanie. Dziennik może być przeciążony lub mieć przerwę techniczną.
`Kod błędu: 51 (w VulcanHebeAddressbook2) Attempt to invoke virtual method 'boolean com.google.gson.l.s()' on a null object reference`"

Błąd występuje w wersjach 4.11.7 i 4.11.8.
Wersja 4.11.6 działa poprawnie.
Używam LineageOS 18.1 (android 11) na Redmi Note 7.

**Comment by kuba2k2** [comment]
Spróbuj na wersji 4.11.9 - powinno działać.
