### ISSUE TITLE
Nie zapisuje się układ strony głównej

### ISSUE THREAD

**Issue by tadekdudek** [szkolny-eu/szkolny-android#153]
Aplikacja nie zapisuje układu strony głównej. Niby edytować się da, ale po restarcie aplikacji wszystko resetuje się do wcześniejszych ustawień. Błąd występuje od którejś z wersji 4.13-beta lub 4.13-rc, nie jestem w stanie sprawdzić, w której dokładnie, ponieważ aplikacja daje się zdowngrade'ować tylko do wersji 4.13-rc5, przy próbach downgrade'owania do starszych wersji wyskakują błędy.

**Comment by kuba2k2** [comment]
Naprawione w v4.13.1.
