### ISSUE TITLE
[Vulcan] Nie da się synchronizować aplikacji, błąd serwera

### ISSUE THREAD

**Issue by MajliTech** [szkolny-eu/szkolny-android#156]
Błąd serwera: plik nie znaleziony
Kod błędu: 54 (on VulcanHebeAdressbok) Response failure exception

Vulcan chyba coś znowu nazmieniał w swoim API.

**Comment by tadekdudek** [comment]
U mnie w wersji 4.13.2-rc2 wszystko działa. Używam logowania przez e-mail i hasło, jeśli to coś zmienia.

**Comment by MajliTech** [comment]
Spróbuje nową wersje, zaczekaj

**Comment by MajliTech** [comment]
Nie ruszy. Cały czas ten sam błąd.

**Comment by kuba2k2** [comment]
Na jedynym koncie jakie mam, nie ma tego błędu. W związku z tym nie mam możliwości tego naprawić.

**Comment by MajliTech** [comment]
To chociaż dodaj oddzielny przełącznik do syncrhonizacji książki adresowej, bo cała klasa ma problemy :(

**Comment by tadekdudek** [comment]
@MajliTech spróbuj z wersją 4.13.2-rc4, myślę, że wtedy powinno zadziałać

**Comment by kuba2k2** [comment]
Tak, już musi działać.

**Comment by MajliTech** [comment]
Dobra, zamykam. Rc-4 działa.
