### ISSUE TITLE
[Vulcan] Błąd przy synchronizacji nowo dodanego konta

### ISSUE THREAD

**Issue by tadekdudek** [szkolny-eu/szkolny-android#157]
Po dodaniu nowego konta Vulcan nie da się niczego synchronizować - zawsze wyskakuje błąd:

Nieprawidłowy podpis zapytania. Sprawdź ustawienia daty i godziny w systemie.
Kod błędu: 360 (w VulcanHebeAdressbook)

Możliwe, że związane z #156.

**Comment by tadekdudek** [comment]
Tak

**Comment by kuba2k2** [comment]
U mnie nadal działa.

**Comment by tadekdudek** [comment]
Naprawiono w wersji 4.13.2-rc4.
