### ISSUE TITLE
Błąd przy ładowaniu odmian dziennika

### ISSUE THREAD

**Issue by tadekdudek** [szkolny-eu/szkolny-android#158]
Podczas ładowania odmian dziennika (Vulcan przy logowaniu przez email i hasło oraz USOS) wyskakuje błąd:

Kod błędu: 2 (w SzkolnyApi)
Kod błędu: 2 (w SzkolnyApi)
Error body does not contain a valid Error.

**Comment by kuba2k2** [comment]
Naprawione.

**Comment by kuba2k2** [comment]
Przy okazji, zapraszam na discorda, takie małe błędy lepiej chyba zgłaszać tam.
