### ISSUE TITLE
Opcja do ignorowania nieobecności nauczycieli

### ISSUE THREAD

**Issue by hrw** [szkolny-eu/szkolny-android#160]
Aplikacja podaje że jutro będzie nieobecnych 7 nauczycieli. Tylko 3 z nich ma zajęcia z klasą mego dziecka.

Fajnie by było móc jakoś określić których nauczycieli nieobecność nie ma znaczenia i może być pomijana przez aplikację.

Apka Librusa chyba w ogóle tego nie podaje, strona Librusa wyświetla 3 nauczycieli, w tym u jednej nauczycielki jest info "8:00 - 10:35" co akurat ma znaczenie bo klasa ma dwie lekcje tego dnia - jedną w czasie gdy nauczycielki nie ma (lekcja została odwołana) i jedną później.

**Comment by kuba2k2** [comment]
Obsługa dziennika firmy Librus nie jest już rozwijana w aplikacji. [Więcej szczegółów](https://szkolny.eu/informacja).

**Comment by hrw** [comment]
ok
