### ISSUE TITLE
Informacja o zastępstwach

### ISSUE THREAD

**Issue by hrw** [szkolny-eu/szkolny-android#161]
Strona Librusa podaje info o zastępstwach:

> Zastępstwo z Imię Nazwisko na lekcji nr: 3 (Historia)

Da się to dodać do aplikacji?

**Comment by kuba2k2** [comment]
Aplikacja obsługuje zastępstwa, są one wyświetlane w planie lekcji. Jeśli plan lekcji nie jest opublikowany przez szkołę, zastępstwa nie będą widoczne - jest to związane z architekturą aplikacji (ścisłym powiązaniem "zastępstwa" z daną "lekcją").

**Comment by hrw** [comment]
Dziękuję, spytam szkołę.
