### ISSUE TITLE
UI: usunięcie dolnego paska

### ISSUE THREAD

**Issue by hrw** [szkolny-eu/szkolny-android#162]
Czy hamburger menu i trzy-kropki menu nie mogą być w górnym pasku? Odrobina więcej miejsca na ekranie i elementy nawigacyjne razem z pozostałymi byłyby w jednym miejscu.

**Comment by kuba2k2** [comment]
Jest otwarty [pull request](https://github.com/szkolny-eu/szkolny-android/pull/146) wprowadzający wygląd Material 3. Być może dolny pasek zmieni się po zmianie wyglądu.

**Comment by santoni0** [comment]
Tak, usunąłem już dolny pasek w #146. (na razie nie wrzuciłem jeszcze na githuba tych większych zmian)

**Comment by santoni0** [comment]
![Screenshot_20221129-103336](https://user-images.githubusercontent.com/66315787/204492439-8529e1fd-c09c-4e48-9a7f-5503ad066d0e.png)
A górny pasek wygląda tak.
