### ISSUE TITLE
Edycja avatara ucznia

### ISSUE THREAD

**Issue by hrw** [szkolny-eu/szkolny-android#163]
Średnio mi pasuje różowy avatar na górnej belce aplikacji. Nie wiem czy kolor jest dobierany losowo czy inaczej.

Może opcja powiązania z kontaktem tak by było tam zdjęcie?

**Comment by kuba2k2** [comment]
Zdjęcie dla profilu da się wybrać w ustawieniach aplikacji. Kolor dobierany jest losowo, lecz na podstawie nazwy profilu (domyślnie imienia i nazwiska).

**Comment by hrw** [comment]
Dziękuję, fotka ustawiona.
