### ISSUE TITLE
[Vulcan/Hebe] Błąd przy synchronizacji

### ISSUE THREAD

**Issue by tadekdudek** [szkolny-eu/szkolny-android#165]
Przy próbie zsynchronizowania czegokolwiek wyskakuje błąd:

VULCAN®: zapytanie zawiera niepoprawne dane
Kod błędu: 361 (w VulcanHebePushConfig)

Błąd występuje zarówno przy logowaniu przez email i hasło, jak i przez token, symbol i pin. Wczoraj była jakaś przerwa techniczna, możliwe, że Vulcan znowu pozmieniał coś w API.

Myślę, że dobrym pomysłem w przypadku Vulcana byłoby przejście na [Wulkanowy SDK](https://github.com/wulkanowy/sdk), dzięki czemu aplikacja byłaby mniej podatna na zmiany w API Vulcana, a dodatkowo umożliwiło by to dodanie nowych funkcji (jak np. informacje o szkole).

**Comment by Marioneq4958** [comment]
[wulkanowy/sdk](https://github.com/wulkanowy/sdk) jest raczej bardziej podatny na zmiany.

**Comment by kuba2k2** [comment]
> Błąd występuje zarówno przy logowaniu przez email i hasło, jak i przez token, symbol i pin. Wczoraj była jakaś przerwa techniczna, możliwe, że Vulcan znowu pozmieniał coś w API.

Potwierdzam błąd, jednak nie jest związany ze zmianami w API. Od wersji 4.11 aplikacja źle serializuje "null" w polu `FirebaseToken`, przez co Vulcan zwraca błąd. Jest to rzadki przypadek, najpewniej twój telefon nie posiada usług Google Play albo z jakiegoś innego powodu nie dostał tokenu powiadomień push.

> Myślę, że dobrym pomysłem w przypadku Vulcana byłoby przejście na [Wulkanowy SDK](https://github.com/wulkanowy/sdk), dzięki czemu aplikacja byłaby mniej podatna na zmiany w API Vulcana, a dodatkowo umożliwiło by to dodanie nowych funkcji (jak np. informacje o szkole).

Szkolny.eu korzysta z tego samego API, co Dzienniczek VULCAN. Jakiekolwiek zmiany w API które "psują" Szkolnego, psują też Dzienniczek VULCAN. Jedynie ostatni błąd ("plik nie znaleziony") nie dotyczył DV, ponieważ Szkolny korzystał z przestarzałego API.

Przejście na Wulkanowy SDK wymagałoby przepisania (dosłownie napisania od nowa) całego modułu API Vulcana, oraz pewnie również innych gruntownych zmian w aplikacji, czego nikomu raczej nie chce się teraz robić.

**Comment by tadekdudek** [comment]
> [wulkanowy/sdk](https://github.com/wulkanowy/sdk) jest raczej bardziej podatny na zmiany.

Chodzi mi o to, że Wulkanowy SDK jest aktywniej rozwijane, więc błędy są szybciej naprawiane.

> Jest to rzadki przypadek, najpewniej twój telefon nie posiada usług Google Play albo z jakiegoś innego powodu nie dostał tokenu powiadomień push.

Używam LineageOS for MicroG bez połączonego konta Google, rejestracja urządzenia Google włączona, Cloud Messaging włączone, Google SafetyNet włączone, używam Universal SafetyNet Fix. Używałem aplikacji szkolny.eu tylko przy takiej konfiguracji. Dotychczas taki błąd nie wyskakiwał. Nie miałem problemów dotyczących usług Google Play z innymi aplikacjami.

> @tadekdudek sprawdź wersję 4.13.3.

Sprawdziłem, działa. Zamykam.
