### ISSUE TITLE
Dodanie ograniczeń webview przy logowaniu do USOS

### ISSUE THREAD

**Issue by tadekdudek** [szkolny-eu/szkolny-android#166]
Niektóre formularze logowania do USOS pozwalają na otwarcie innych stron. Powinno być to ograniczone.

![gif](https://user-images.githubusercontent.com/99012892/208605037-7f8d747e-2641-4867-9a48-4e32fa023741.gif)

**Comment by kuba2k2** [comment]
Formularze logowania lubią przechodzić między domenami do autoryzacji, ciężko będzie mi przewidzieć jakie domeny powinny być dozwolone, a jakie powinny otwierać nowe okno.
