### ISSUE TITLE
Błąd przy ładowaniu listy odmian dziennika

### ISSUE THREAD

**Issue by tadekdudek** [szkolny-eu/szkolny-android#168]
Przy próbie zalogowania się do Vulcana przez email i hasło lub do USOS wyskakuje błąd:

Kod błędu: 2 (w SzkolnyApi)
Kod błędu: 2 (w SzkolnyApi)
Error body does not contain a valid Error.

Ten sam błąd co #158.

**Comment by kuba2k2** [comment]
Naprawione.
