### ISSUE TITLE
No permission to download attachment

### ISSUE THREAD

**Issue by M3DZIK** [szkolny-eu/szkolny-android#172]
Nie można pobrać załączników ponieważ aplikacja nie ma uprawnień do storage.

![Screenshot_20230131-110515_Szkolny eu_1](https://user-images.githubusercontent.com/87065584/215736133-715d9299-e551-4284-b1c3-a5e3934bd707.png)

![Screenshot_20230131-112606_Permission controller](https://user-images.githubusercontent.com/87065584/215736326-9285283d-2672-472f-832d-222e5e957be4.png)

nie można nadać uprawnień do pamięci telefonu (a przynajmniej nie widzę takiej opcji)

- Android 13

*Nie posiadam Google Mobile Services

**Comment by tadekdudek** [comment]
U mnie też jest taki problem

**Comment by kuba2k2** [comment]
Naprawione w wersji 4.13.5 chyba

**Comment by M3DZIK** [comment]
Wydaje się działać, Dzięki!
