### ISSUE TITLE
Can't open the app.

### ISSUE THREAD

**Issue by ignatyb** [szkolny-eu/szkolny-android#174]
Sorry for using English, but my Polish is kinda bad. So, I can't open the app: it simply crashes. Not sure why. It doesn't give any error, it just crashes. Worked perfectly fine before. I can't attach the logs because it crashes before showing the R.I.P. screen. My guess it is because I deleted some apps with adb recently ([the full list of them](https://pastebin.com/YgZUNZQr) ), but there weren't any essentials and all the apps are working properly except szkolny.eu.

**Comment by tadekdudek** [comment]
Probably it is caused by removing Google Play Services (com.google.android.gms) and Google Services Framework (com.google.android.gsf), maybe it is something related to Cloud Messaging. Install MicroG, reinstall Google Play Services and GSF or wipe app data.

**Comment by ignatyb** [comment]
Reinstalling Google Play Services (`adb shell cmd package install-existing com.google.androis.gms`) helped, thank you!

**Comment by kuba2k2** [comment]
That's odd, there shouldn't be any hard dependency on GMS. You can try the APK version from the website instead.

**Comment by ignatyb** [comment]
I am using Librus, so yeah, I use APK version from the website
