### ISSUE TITLE
Dodanie themed icon

### ISSUE THREAD

**Issue by M3DZIK** [szkolny-eu/szkolny-android#179]
Prosimy o dodanie themed icon (dostępnej od Androida 13+). Ponieważ ikona aplikacji wyróżnia się i wygląda brzydko w porównaniu do innych.

![signal-2023-08-31-235150](https://github.com/szkolny-eu/szkolny-android/assets/87065584/dda346a5-839f-4e26-b7f0-e4ff5de8a7b2)

**Comment by kuba2k2** [comment]
#146

**Comment by kuba2k2** [comment]
@santoni0

**Comment by M3DZIK** [comment]
jest gdzieś svg ikonki aplikacji?

**Comment by kuba2k2** [comment]
![logo_optimized](https://github.com/szkolny-eu/szkolny-android/assets/30433568/370c0784-3c3c-4dd1-aef0-01486360e051)

**Comment by M3DZIK** [comment]
okej, dzięki to mogę za jakiś czas dodać

**Comment by santoni0** [comment]
cały PR względnie leży w tej chwili, ale akurat to w nim działa dość dobrze
![Screenshot 2023-09-04 153210](https://github.com/szkolny-eu/szkolny-android/assets/66315787/4f366086-2189-4224-b4de-e9e52edec8d3)

**Comment by wojtekojtek** [comment]
> cały PR względnie leży w tej chwili (wracałem do niego ostatnio, tyle że nowa wersja MD crashuje apkę i muszę to naprawić), ale akurat to w nim działa dość dobrze ![Screenshot 2023-09-04 153210](https://user-images.githubusercontent.com/66315787/265473799-4f366086-2189-4224-b4de-e9e52edec8d3.png)

Wygląda świetnie :D 
Nie mogę się doczekać, ponieważ 
![image](https://github.com/szkolny-eu/szkolny-android/assets/49075395/af6bd1f2-2604-4411-ac94-21da02d3f7e8)
przestał pracować nad szkolnym.......

**Comment by kuba2k2** [comment]
Zdarza się
https://szkolny.eu/informacja

**Comment by wojtekojtek** [comment]
> Jak zapewne już wiecie, we wrześniu 2020r. firma Librus zabroniła nam publikowania **w sklepie Google Play** naszej aplikacji z obsługą dziennika Librus® Synergia, pod groźbą wejścia na drogę sądową.
Ale to w sklepie Play, nie na githubie, po za tym, aplikacja mogłaby być dalej rozwijana, ale bez publikowania w sklepie play.....................

**Comment by wojtekojtek** [comment]
![image](https://github.com/szkolny-eu/szkolny-android/assets/49075395/5f97e732-2d55-4059-8aac-da6d72ca757d)
nadal siedzi

![image](https://github.com/szkolny-eu/szkolny-android/assets/49075395/5a257738-7857-414f-9556-e55a724d5dbe)
w 2020r.

![image](https://github.com/szkolny-eu/szkolny-android/assets/49075395/5d320062-726d-4daa-b96c-c09379008a06)
ostatnia aktualizacja z 2023 roku 🤡

**Comment by kuba2k2** [comment]
To że jest w Google Play, to nie znaczy że jest w niej librus.

**Comment by Roki100** [comment]
> To że jest w Google Play, to nie znaczy że jest w niej librus.

ale https://github.com/szkolny-eu/szkolny-android/issues/179#issuecomment-1705561598 ma racje

**Comment by wojtekojtek** [comment]
> To że jest w Google Play, to nie znaczy że jest w niej librus.

sprawdziłem, i jest. :|
nie mogłem od razu odpisać więc odpisuję teraz

**Comment by M3DZIK** [comment]
> > To że jest w Google Play, to nie znaczy że jest w niej librus.
> 
> sprawdziłem, i jest. :| nie mogłem od razu odpisać więc odpisuję teraz

nie zalogujesz sie
