### ISSUE TITLE
Nazwy przedmiotów na planie lekcji nie są wczytywane

### ISSUE THREAD

**Issue by kubabisi** [szkolny-eu/szkolny-android#181]
Wersja aplikacji: 4.13.6
Dziennik: Librus

Tak jak w tytule, nazwy przedmiotów na planie lekcji nie są wczytywane.

![Screenshot_20230904_124527_Szkolnyeu](https://github.com/szkolny-eu/szkolny-android/assets/135463288/927af5b0-c74f-4c91-becc-117010ab108c)
![Screenshot_20230904_124543_Szkolnyeu](https://github.com/szkolny-eu/szkolny-android/assets/135463288/5fdbb031-df9e-4955-80b1-848d7069aa9d)
![Screenshot_20230904_130801_Szkolnyeu](https://github.com/szkolny-eu/szkolny-android/assets/135463288/e71fa5b8-1cb3-4f7f-bd79-34d4f6f9f400)

![Screenshot_20230904_125204_Firefox](https://github.com/szkolny-eu/szkolny-android/assets/135463288/fe5ec95b-62f1-44a9-80c1-67a562a099b6)

**Comment by kuba2k2** [comment]
Proszę się wylogować i zalogować ponownie.

**Comment by kubabisi** [comment]
Zadziałało
