### ISSUE TITLE
Przeformatowanie karty 'Dzisiaj'?

### ISSUE THREAD

**Issue by hrw** [szkolny-eu/szkolny-android#184]
Teraz to wygląda tak:

![obraz](https://github.com/szkolny-eu/szkolny-android/assets/185508/219d7f38-ebb0-4b94-8e83-808e9fb3ea28)

A gdyby listę lekcji zrobić z formatowanym czasem?

` 8:55` Geografia
` 9:50` Matematyka
`11:05` Wiedza o społeczeństwie
`12:00` Historia
`12:55` Biologia
`13:50` Język polski
`14:45` Informatyka

Wtedy nazwy lekcji i terminy byłyby wyrównane w pionie a przez to czytelniejsze.

**Comment by kuba2k2** [comment]
Zastąpione przez #196, rozwiązane w #201.
