### ISSUE TITLE
Błąd SynergiaTokenExtractor

### ISSUE THREAD

**Issue by QBANIN** [szkolny-eu/szkolny-android#197]
Dzisiaj po ponad roku korzystania przywitał mnie taki komunikat. Zalogowałem się przez www ale nie wiem o co chodzi z naprawą konta
[Screenshot_20240426_083838_Szkolnyeu.jpg](https://github.com/szkolny-eu/szkolny-android/assets/487657/07294bf9-15ab-46e1-91d4-ea8d9e0ea0a1)

**Comment by kuba2k2** [comment]
Proponuję zrobić to co jest napisane w tym błędzie. Zaloguj się w oficjalnej aplikacji i napraw powiązanie konta.

**Comment by QBANIN** [comment]
Instrukcje są niejasne ale już sobie poradziłem.
