### ISSUE TITLE
Wersja cmake ustawiona na sztywno

### ISSUE THREAD

**Issue by tomaszk8266** [szkolny-eu/szkolny-android#204]
Wersja cmake jest ustawiona na sztywno, tylko po co? I to na 3.10.2 sprzed 6 lat?

**Comment by kuba2k2** [comment]
Bo działa :smiley:

**Comment by tomaszk8266** [comment]
Nowa też działa, a teraz trzeba zawsze zmieniać albo doinstalowywać starą

**Comment by kuba2k2** [comment]
Ja tam nigdy nie musiałem nic instalować. A jest tak ustawiona, bo jak nie była to nie działało.

**Comment by tomaszk8266** [comment]
Też działa

![obraz](https://github.com/szkolny-eu/szkolny-android/assets/164745051/f96cb211-4f47-4797-878c-6a032a25e000)

**Comment by kuba2k2** [comment]
Można pewnie usunąć.

**Comment by kuba2k2** [comment]
Jest już usunięte.
