### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by Klubuntu** [szkolny-eu/szkolny-android#43]
Czy jest możliwość zmiany nazwy Szkolny.eu na nazwę Szkolny.eu Vulcan Mobidziennik IDziennik, ponieważ Librus nie jest już wspierany, czy jest możliwość kontaktu ze mną przez Email : klubuntu.soft@gmail.com.
Dziękuję za przyjęcie mojej propozycji

**Comment by MarcinK50** [comment]
Dziennik Librus jest wspierany, tylko nieoficjalnie na GitHubie :/

**Comment by kuba2k2** [comment]
Nothing here to work on, closing.
