### ISSUE TITLE
Other entries in attendance and in the calendar

### ISSUE THREAD

**Issue by MaksDradrach** [szkolny-eu/szkolny-android#44]
Hello,
in the application version 4.7.1, in the schedule and the attendance tab, there are entries that I normally do not have on the librus. Can they be removed somehow? I am sending attachments. If I can, I will add a request for 2 new functions: adding my own timetable and deleting or hiding announcements. 
![Screenshot_20210425-100710](https://user-images.githubusercontent.com/83159210/115986287-c9e4b180-a5af-11eb-884a-f1f9362ade0f.png)
![Screenshot_20210425-100725](https://user-images.githubusercontent.com/83159210/115986292-ccdfa200-a5af-11eb-9184-a108c4421712.png)

**Comment by kuba2k2** [comment]
Librus is not officially supported anymore in the app, and won't be worked on by the original author. You can ask the community to fix your problem, or fix it yourself.

**Comment by kuba2k2** [comment]
Also, @MaksDradrach, you can hide the red teacher absence items in the agenda settings.
