### ISSUE TITLE
Opcja wyłączenia powiadomienia o pobieraniu danych

### ISSUE THREAD

**Issue by acidioxide** [szkolny-eu/szkolny-android#49]
Opcja wyłączenia powiadomienia, które pojawia się za każdym razem gdy szkolny pobiera dane z dziennika.
![Screenshot_20210527-220722.png](https://user-images.githubusercontent.com/82203150/119890326-fafe2c00-bf37-11eb-9de1-0ce386d48e04.png)

**Comment by kuba2k2** [comment]
Takie jest wymaganie Androida - usługa działająca w tle musi wyświetlać powiadomienie, inaczej nie działa to dobrze, czyli Android często zamyka aplikację. Wtedy dane się nie synchronizują i nie pojawiają się powiadomienia.

**Comment by acidioxide** [comment]
A opcja zmniejszenia baneru / zmiany ikony? Często gdy wyskakuje, myślę że przyszło powiadomienie

**Comment by kuba2k2** [comment]
Ikonę można wyłączyć w ustawieniach powiadomień - domyślnie, aplikacja ustawia ją jako wyłączoną, ale Android ignoruje to ustawienie w nowych wersjach i należy zrobić to ręcznie. Nazywa się to chyba "minimalizuj powiadomienie" lub coś podobnego.

**Comment by acidioxide** [comment]
o to mi chodziło, dzięki :-D
