### ISSUE TITLE
Downloading attachments not working on Android 11

### ISSUE THREAD

**Issue by BulletBlaster** [szkolny-eu/szkolny-android#58]
When attempting to download an attachment from a message on ArrowOS 11.0 (Android 11.0) I'm getting the following error:

`Kod błędu: 50 (on LibrusSandboxDownloadAttachment)
/storage/emulated/0/Szkolny.eu/file.ext: open failed: ENOENT (No such file or directory)`

After manually creating the "Szkolny.eu" folder the error is different:

`Kod błędu: 50 (on LibrusSandboxDownloadAttachment)
/storage/emulated/0/Szkolny.eu/file.ext: open failed: EPERM (Operation not permitted)`

I've already allowed Szkolny.eu to access photos and media in the respective dialog.

After checking the permissions granted to the app in settings it appears as Szkolny.eu doesn't request full storage access which would be needed to create folders and files in the internal storage - I can only switch between "Allow access to media only" and "Deny".

**Comment by kuba2k2** [comment]
Maybe related to #57? @doteq

**Comment by doteq** [comment]
Yeah, #57 fixes that exact issue.
