### ISSUE TITLE
Nieprawidłowy kod klienta

### ISSUE THREAD

**Issue by Bartkk0** [szkolny-eu/szkolny-android#87]
Kod błędu: 126 (w LoginLibrusApi)

**Comment by kuba2k2** [comment]
Proszę podać więcej szczegółów dotyczących tego błędu.

**Comment by Bartkk0** [comment]
Nieprawidłowy kod klienta przy synchronizacji danych na koncie librus przez platformę V
![Screenshot_20211006-093357_Szkolny eu](https://user-images.githubusercontent.com/32180149/136159810-980bf110-d196-484b-8780-56412491a4be.png)
ULCAN.

**Comment by Bartkk0** [comment]
Ponowne dodanie konta naprawiło problem

**Comment by kuba2k2** [comment]
Jako że dziennik Librus nie jest już oficjalnie wspierany (https://szkolny.eu/informacja), zostawiam to zgłoszenie do rozwiązania przez innych deweloperów.
